config/routes.rb
Zadziory::Application.routes.draw do

  resources :requests

  resources :authentications

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :preferences

  resources :places

  resources :histories

  resources :user_panel

  devise_for :users
  
  devise_scope :user do
	get "login", :to => "devise/sessions#new" 
	get "logout", :to => "devise/sessions#destroy"
	get "register", :to => "devise/registrations#new"
  end
  
  devise_for :users, :controllers => {:registrations => 'registrations'}
  
  match '/auth/:provider/callback' => 'authentications#create'

	get '/users/:id' => 'users#show', :as => "user"

		root :to => "places#index"

	get "myplaces" => "places#myPlaces", :as => "myplaces"
	get "panel" => "user_panel#index", :as => "panel"
	get "undefined" => "application#undefined_error", :as => "undefined"
	get '/user' => 'users#myAccount', :as => "my_account"

  get "allTenantRequests" => "requests#allTenantRequests", :as => "all_tenant_requests"
  get "pendingTenantRequests" => "requests#pendingTenantRequests", :as => "pending_tenant_requests"
  get "acceptedTenantRequests" => "requests#acceptedTenantRequests", :as => "accepted_tenant_requests"
  get "rentedTenantRequests" => "requests#rentedTenantRequests", :as => "rented_tenant_requests"
  get "rejectedTenantRequests" => "requests#rejectedTenantRequests", :as => "rejected_tenant_requests"

  get "allOwnerRequests" => "requests#allOwnerRequests", :as => "all_owner_requests"
  get "pendingOwnerRequests" => "requests#pendingOwnerRequests", :as => "pending_owner_requests"
  get "acceptedOwnerRequests" => "requests#acceptedOwnerRequests", :as => "accepted_owner_requests"
  get "rentedOwnerRequests" => "requests#rentedOwnerRequests", :as => "rented_owner_requests"
  get "rejectedOwnerRequests" => "requests#rejectedOwnerRequests", :as => "rejected_owner_requests"
end

app/models/request.rb
class Request < ActiveRecord::Base
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  # GET /preferences
  # GET /preferences.xml
  def index
    @requests = Request.all
    respond_with(@requests)
  end

  # GET /preferences/1
  # GET /preferences/1.xml
  def show
    @request = Request.find(params[:id])
    respond_with(@request)
  end

  # GET /preferences/new
  # GET /preferences/new.xml
  def new
    @request = Request.new
    respond_with(@request)
  end

  # GET /preferences/1/edit
  def edit
    @request = Request.find(params[:id])
  end

  # POST /preferences
  # POST /preferences.xml
  def create
    @request = Request.new(params[:request])
    @request.user_id = current_user.id
    @request.owner_id = User.find(Place.find(params[:request][:place_id]).user_id).id
    @request.status = 1
    @request.save
    #respond_with(@request)
    redirect_to  pending_tenant_requests_path and return
  end

  # PUT /preferences/1
  # PUT /preferences/1.xml
  def update
    @request = Request.find(params[:id])
    @request.update_attributes(params[:request])
    #respond_with(@request)
    case params[:request][:status]
      when "0"
         redirect_to  rejected_owner_requests_path and return
       when "1"
         redirect_to  pending_owner_requests_path and return
       when "2"
         redirect_to  accepted_owner_requests_path and return
       when "3"
         redirect_to  rented_owner_requests_path and return
    end
  end

  # DELETE /preferences/1
  # DELETE /preferences/1.xml
  def destroy
    @request = Request.find(params[:id])
    @request.destroy
    respond_with(@request)
  end

  # actions for TENANT
  def allTenantRequests
    @requests = Request.find_all_by_user_id(current_user.id)
	  render 'requests/index'
  end
  def pendingTenantRequests
    @requests = Request.find(:all, :conditions => { :status => 1, :user_id => current_user.id })
	  render 'requests/index'
  end
  def acceptedTenantRequests
    @requests = Request.find(:all, :conditions => { :status => 2, :user_id => current_user.id })
	  render 'requests/index'
  end
  def rentedTenantRequests
    @requests = Request.find(:all, :conditions => { :status => 3, :user_id => current_user.id })
	  render 'requests/index'
  end
  def rejectedTenantRequests
    @requests = Request.find(:all, :conditions => { :status => 0, :user_id => current_user.id })
	  render 'requests/index'
  end


  #actions for OWNER
   def allOwnerRequests
    @requests = Request.find_all_by_owner_id(current_user.id)
	  render 'requests/index'
   end
   def pendingOwnerRequests
    @requests = Request.find(:all, :conditions => { :status => 1, :owner_id => current_user.id })
	  render 'requests/index'
  end
  def acceptedOwnerRequests
    @requests = Request.find(:all, :conditions => { :status => 2, :owner_id => current_user.id })
	  render 'requests/index'
  end
  def rentedOwnerRequests
    @requests = Request.find(:all, :conditions => { :status => 3, :owner_id => current_user.id })
	  render 'requests/index'
  end
  def rejectedOwnerRequests
    @requests = Request.find(:all, :conditions => { :status => 0, :owner_id => current_user.id })
	  render 'requests/index'
  end

end

app/helpers/requests_helper.rb
module RequestsHelper

  def get_status(status)
     case status
       when 0
         "rejected"
       when 1
         "pending"
       when 2
         "accepted"
       when 3
         "rented"
       when String
         "error - string passed"
       else
         "error"
     end
  end


  # options => :all  return all options
  # options => :pending return options for pending status (accepted/rejected)
  # options => :accepted return options for accepted status (rented/rejected)
  def get_status_collection(options)
    case options
      when :all
        {get_status(1) => 1, get_status(2) => 2, get_status(3) => 3, get_status(0) => 0}
      when :pending
        {get_status(2) => 2, get_status(0) => 0}
      when :accepted
        {get_status(3) => 3, get_status(0) => 0}
    end

  end

end

app/views/requests/_form.html.erb
<%= semantic_form_for @request do |f| %>
  <%= f.inputs do %>
    <%= f.input :place_id, :as => :hidden, :input_html => {:value => params[:place_id]} %>
    <%= f.input :date_start, :as => :string , :input_html => { :class => "date_stealer", :size => 30 } %>
    <%= f.input :date_end, :as => :string , :input_html => { :class => "date_stealer", :size => 30 } %>
    <%= f.input :number_of_people, :input_html => { :size => 5 } %>
    <%= f.input :people_type, :input_html => { :size => 30 } %>
    <%= f.input :message %>
  <% end %>

  <%= f.buttons do %>
    <%= f.commit_button %>
  <% end %>
<% end %>

app/views/requests/_nav.html.erb
<div id="nav">
  <% if can? :myTenantRequests, Request %>
        <%= link_to t('requests.nav.all'), all_tenant_requests_path , class: "btn primary" %>
        <%= link_to t('requests.nav.pending'), pending_tenant_requests_path, class: "btn primary" %>
        <%= link_to t('requests.nav.accepted'), accepted_tenant_requests_path, class: "btn primary" %>
        <%= link_to t('requests.nav.rented'), rented_tenant_requests_path, class: "btn primary" %>
        <%= link_to t('requests.nav.rejected'), rejected_tenant_requests_path, class: "btn primary" %>
    <% end %>
   <% if can? :myOwnerRequests, Request %>
        <%= link_to t('requests.nav.all'), all_owner_requests_path , class: "btn primary" %>
        <%= link_to t('requests.nav.pending'), pending_owner_requests_path, class: "btn primary" %>
        <%= link_to t('requests.nav.accepted'), accepted_owner_requests_path, class: "btn primary" %>
        <%= link_to t('requests.nav.rented'), rented_owner_requests_path, class: "btn primary" %>
        <%= link_to t('requests.nav.rejected'), rejected_owner_requests_path, class: "btn primary" %>
    <% end %>

</div>

app/views/requests/_request.html.erb
<article class="request">
  <% if current_user.has_role? :tenant  %>
        <div class="attribute">
        <span class="name"><%= t('requests.request.owner') %></span>
        <span class="value"><%= link_to get_user_username(request.owner_id), user_path(request.user_id)%></span>
      </div>
  <% end %>
  <% if current_user.has_role? :owner  %>
      <div class="attribute">
        <span class="name"><%= t('requests.request.user') %></span>
        <span class="value">    <%= link_to get_user_username(request.user_id), user_path(request.user_id)%></span>
      </div>
  <% end %>
  <% if current_user.has_role? :tenant and (get_status(request.status) == "accepted" or get_status(request.status) == "rented") %>
      <div class="attribute">
        <span class="name"><%= t('requests.request.telephone') %></span>
        <span class="value">    <%= get_place_telephone(request.place_id) %></span>
      </div>
      <div class="attribute">
        <span class="name"><%= t('requests.request.adress') %></span>
        <span class="value">    <%= get_place_address(request.place_id)%></span>
      </div>
  <% end %>
    <div class="attribute">
    <span class="name"><%= t('requests.request.place') %></span>
      <span class="value"><%= link_to request.place_id.to_s, place_path(request.place_id) %></span>
  </div>
    <div class="attribute">
    <span class="name"><%= t('requests.request.status') %></span>
      <span class="value"><%= get_status(request.status) %></span>
  </div>
    <div class="attribute">
    <span class="name"><%= t('requests.request.start') %></span>
    <span class="value"><%= request.date_start %></span>
  </div>
    <div class="attribute">
    <span class="name"><%= t('requests.request.end') %></span>
    <span class="value"><%= request.date_end %></span>
  </div>
    <div class="attribute">
    <span class="name"><%= t('requests.request.people') %></span>
    <span class="value"><%= request.number_of_people %></span>
  </div>
    <div class="attribute">
    <span class="name"><%= t('requests.request.people_type') %></span>
    <span class="value"><%= request.people_type %></span>
  </div>
    <div class="attribute">
    <span class="name"><%= t('requests.request.message') %></span>
    <span class="value"><%= request.message %></span>
  </div>
  <div>
    <% if current_user.has_role? :owner  %>
        <% if get_status(request.status) == "pending" %>
            <%= semantic_form_for request do |f| %>
              <%= f.inputs do %>
                <%= f.input :status, :as => :select, :collection => get_status_collection(:pending), :include_blank => false %>
              <% end %>

              <%= f.buttons do %>
                <%= f.commit_button :button_html => { :confirm => "Are you sure?" } %>
              <% end %>
            <% end %>
        <% end %>
        <% if  get_status(request.status) == "accepted" %>
           <%= semantic_form_for request do |f| %>
              <%= f.inputs do %>
                <%= f.input :status, :as => :select, :collection => get_status_collection(:accepted), :include_blank => false %>
              <% end %>

              <%= f.buttons do %>
                <%= f.commit_button :button_html => { :confirm => "Are you sure?" } %>
              <% end %>
            <% end %>
        <% end %>
    <% end %>
  </div>
</article>

app/views/requests/edit.html.erb
<% title t('requests.edit.title') %>

<div class="form edit">
  <%= render 'form' %>
  <div class="link">
    <%= link_to t('place.edit.show'), @request, class: "btn primary" %>
    <%= link_to t('place.edit.back'), requests_path, class: "btn primary" %>
  </div>
</div>

app/views/requests/index.html.erb
<%= render 'nav' %>
<% title t('requests.index.title') %>


<article class="requests">
    <%= render :partial => 'request', :collection => @requests %>
</article>

app/views/requests/new.html.erb
<% title t('requests.new.title') %>

<div class="form new">
  <%= render 'form' %>
  <div class="link">
    <%= link_to 'Back', requests_path, class: "btn primary" %>
  </div>
</div>

app/views/requests/show.html.erb
<% title t('requests.show.title') %>

<% if notice -%>
<div id="notice"><%= notice %></div>
<% end -%>

<article class="single">
  <div class="attribute">
    <span class="name"><%= t('requests.show.user') %></span>
    <span class="value">    <%= link_to get_user_username(@request.user_id), user_path(@request.user_id)%></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t('requests.show.place') %></span>
    <span class="value"><%= link_to @request.place_id.to_s, place_path(@request.place_id) %></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t('requests.show.status') %></span>
    <span class="value"><%= get_status(@request.status) %></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t('requests.show.start') %></span>
    <span class="value"><%= @request.date_start %></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t('requests.show.end') %></span>
    <span class="value"><%= @request.date_end %></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t('requests.show.people') %></span>
    <span class="value"><%= @request.number_of_people %></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t('requests.show.people_type') %>/span>
    <span class="value"><%= @request.people_type %></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t('requests.show.message') %></span>
    <span class="value"><%= @request.message %></span>
  </div>
  <div class="link">
    <%= link_to 'Edit', edit_request_path(@request), class: "btn primary" %>
    <%= link_to 'Back', requests_path, class: "btn primary" %>
  </div>
</article>