config/routes.rb
Zadziory::Application.routes.draw do

  resources :requests

  resources :authentications

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :preferences

  resources :places

  resources :histories

  resources :user_panel

  devise_for :users
  
  devise_scope :user do
	get "login", :to => "devise/sessions#new" 
	get "logout", :to => "devise/sessions#destroy"
	get "register", :to => "devise/registrations#new"
  end
  
  devise_for :users, :controllers => {:registrations => 'registrations'}
  
  match '/auth/:provider/callback' => 'authentications#create'

	get '/users/:id' => 'users#show', :as => "user"

		root :to => "places#index"

	get "myplaces" => "places#myPlaces", :as => "myplaces"
	get "panel" => "user_panel#index", :as => "panel"
	get "undefined" => "application#undefined_error", :as => "undefined"
	get '/user' => 'users#myAccount', :as => "my_account"

  get "allTenantRequests" => "requests#allTenantRequests", :as => "all_tenant_requests"
  get "pendingTenantRequests" => "requests#pendingTenantRequests", :as => "pending_tenant_requests"
  get "acceptedTenantRequests" => "requests#acceptedTenantRequests", :as => "accepted_tenant_requests"
  get "rentedTenantRequests" => "requests#rentedTenantRequests", :as => "rented_tenant_requests"
  get "rejectedTenantRequests" => "requests#rejectedTenantRequests", :as => "rejected_tenant_requests"

  get "allOwnerRequests" => "requests#allOwnerRequests", :as => "all_owner_requests"
  get "pendingOwnerRequests" => "requests#pendingOwnerRequests", :as => "pending_owner_requests"
  get "acceptedOwnerRequests" => "requests#acceptedOwnerRequests", :as => "accepted_owner_requests"
  get "rentedOwnerRequests" => "requests#rentedOwnerRequests", :as => "rented_owner_requests"
  get "rejectedOwnerRequests" => "requests#rejectedOwnerRequests", :as => "rejected_owner_requests"
end

app/controllers/user_panel_controller.rb
class UserPanelController < ApplicationController
end

app/views/user_panel/index.html.erb
<% title t('user_panel.label')  %>

<article class="single">

 <div class="link">
	<% if can? :read , Place %>
		<%= link_to t('user_panel.index.all_places'), places_path, class: "btn primary" %>
	<% end %>
	<% if can? :myPlaces, Place %>
		<%= link_to t('user_panel.index.my_places'), myplaces_path , class: "btn primary" %>
	<% end %>
    <% if can? :myTenantRequests, Request %>
        <%= link_to t('user_panel.index.request'), all_tenant_requests_path , class: "btn primary" %>
    <% end %>
   <% if can? :myOwnerRequests, Request %>
        <%= link_to t('user_panel.index.request'), all_owner_requests_path , class: "btn primary" %>
    <% end %>
    <%= link_to t('user.my.info'), my_account_path , class: "btn primary" %>
 </div>

</article>