config/routes.rb
Zadziory::Application.routes.draw do

  resources :requests

  resources :authentications

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :preferences

  resources :places

  resources :histories

  resources :user_panel

  devise_for :users
  
  devise_scope :user do
	get "login", :to => "devise/sessions#new" 
	get "logout", :to => "devise/sessions#destroy"
	get "register", :to => "devise/registrations#new"
  end
  
  devise_for :users, :controllers => {:registrations => 'registrations'}
  
  match '/auth/:provider/callback' => 'authentications#create'

	get '/users/:id' => 'users#show', :as => "user"

		root :to => "places#index"

	get "myplaces" => "places#myPlaces", :as => "myplaces"
	get "panel" => "user_panel#index", :as => "panel"
	get "undefined" => "application#undefined_error", :as => "undefined"
	get '/user' => 'users#myAccount', :as => "my_account"

  get "allTenantRequests" => "requests#allTenantRequests", :as => "all_tenant_requests"
  get "pendingTenantRequests" => "requests#pendingTenantRequests", :as => "pending_tenant_requests"
  get "acceptedTenantRequests" => "requests#acceptedTenantRequests", :as => "accepted_tenant_requests"
  get "rentedTenantRequests" => "requests#rentedTenantRequests", :as => "rented_tenant_requests"
  get "rejectedTenantRequests" => "requests#rejectedTenantRequests", :as => "rejected_tenant_requests"

  get "allOwnerRequests" => "requests#allOwnerRequests", :as => "all_owner_requests"
  get "pendingOwnerRequests" => "requests#pendingOwnerRequests", :as => "pending_owner_requests"
  get "acceptedOwnerRequests" => "requests#acceptedOwnerRequests", :as => "accepted_owner_requests"
  get "rentedOwnerRequests" => "requests#rentedOwnerRequests", :as => "rented_owner_requests"
  get "rejectedOwnerRequests" => "requests#rejectedOwnerRequests", :as => "rejected_owner_requests"
end

app/models/place.rb
class Place < ActiveRecord::Base

	belongs_to :user
	has_one :preference
	has_many :histories, :dependent => :destroy
  has_many :images, :dependent => :destroy
  accepts_nested_attributes_for :images, :reject_if => :all_blank, :allow_destroy => true


	scope :inactive, where(:is_active => false)
	scope :active, where(:is_active => true)

	#PRICE_MIN#
	validates :price_min, :numericality => true
	validates_numericality_of :price_min, :less_than_or_equal_to  => :price_max
	validates_numericality_of :price_min, :greater_than_or_equal_to   => 0

	#PRICE_MAX#
	validates :price_max, :numericality => true
	#validates_numericality_of :price_min, :less_than_or_equal_to  =>  9000
	validates_numericality_of :price_max, :greater_than_or_equal_to   => 0

	#BUILD_YEAR#
	validates :build_year, :numericality => true
	validates_numericality_of :build_year, :less_than_or_equal_to  =>  2012
	
	#availability_from#
	validates_date :availability_from, :on_or_after => Date.current, :on_or_after_message => "Z\u{0142}a data"
	
	#Availability_to#
	validates_date :availability_to, :on_or_after => :availability_from, :on_or_after_message => "Z\u{0142}a data"
	
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  load_and_authorize_resource

  # zmienna do paginacji
  $p = 7

  # GET /places
  # GET /places.xml
  def index
	  @search = Place.search(params[:search])
    @places = @search.page(params[:page]).per($p)
  end

  # GET /places/1
  # GET /places/1.xml
  def show
    @place = Place.find(params[:id])
    respond_with(@place)
  end

  # GET /places/new
  # GET /places/new.xml
  def new
    @place = Place.new
	3.times do
      @place.images.build
	end
    respond_with(@place)
  end

  # GET /places/1/edit
  def edit
    @place = Place.find(params[:id])
    if @place.images.empty?
	3.times do
      @place.images.build
    end
    end
    respond_with(@place)
  end

  # POST /places
  # POST /places.xml
  def create
	  @place = current_user.places.build(params[:place])
	  @place.save
	  respond_with(@place)
  end

  # PUT /places/1
  # PUT /places/1.xml
  def update
    @place = Place.find(params[:id])
    params[:place][:images_attributes].each_key { |key|
     if params[:place][:images_attributes][key.to_sym][:remove_image] == "1"
       @image = Image.find(params[:place][:images_attributes][key.to_sym][:id])
       @image.remove_image!
       @image.destroy
       params[:place][:images_attributes].delete(key.to_sym)
     end
    }

    @place.update_attributes(params[:place])
    respond_with(@place)
  end

  # DELETE /places/1
  # DELETE /places/1.xml
  def destroy
    @place = Place.find(params[:id])
    for image in @place.images
        image.remove_image!
        image.destroy
    end
    @place.destroy
    respond_with(@place)
  end

  def myPlaces
	  @search = Place.joins(:user).where("user_id == #{current_user.id}" ).search(params[:search])
	  @places = @search.page(params[:page]).per($p)
	  render 'index'
  end

=begin
  def update_region_select
     @regions = regions_select(params[:country]) unless params[:country].blank?
    render :partial => "regions", :locals => { :regions => @regions }
  end
=end
end

app/helpers/places_helper.rb
module PlacesHelper

  def get_place_telephone(id)
    Place.find(id).telephone.to_s
  end

  def get_place_address(id)
    place = Place.find(id)
    "#{place.street} #{place.place_nr}/#{place.flat_nr}"
  end

end

app/views/places/_form.html.erb
<div id="form">
<%= semantic_form_for @place, :html => { :multipart => true} do |f| %>
  <%= f.inputs do %>
    <%= f.input :availability_from, :as => :string , :input_html => { :class => "date_stealer", :size => 30 } %>
    <%= f.input :availability_to, :as => :string , :input_html => { :class => "date_stealer", :size => 30 } %>
    <%= f.input :price_min, :input_html => { :size => 5 }, :hint => t('place.show.price_min') %>
    <%= f.input :price_max, :input_html => { :size => 5 }, :hint => t('place.show.price_max') %>
    <%= f.input :deposit, :input_html => { :size => 5 } , :hint => t('place.show.deposit') %>
    <%= f.input :grade , :input_html => { :size => 5 }, :hint => t('place.show.grade') %>
    <%= f.input :telephone, :input_html => { :size => 30 } , :hint => t('place.show.telephone') %>
    <%= f.input :country, :priority_countries => [:pl, :gb, :de], :hint => t('place.show.country') %>
	<%= f.input :region,:as => :select, :collection => REGIONS_PL.sort , :hint => t('place.show.region') %>
    <%= f.input :city, :input_html => { :size => 30 } , :hint => t('place.show.city') %>
    <%= f.input :district, :input_html => { :size => 30 } , :hint => t('place.show.district') %>
    <%= f.input :street, :input_html => { :size => 30 } , :hint => t('place.show.street') %>
    <%= f.input :place_nr, :input_html => { :size => 3 }  , :hint => t('place.show.place_nr') %>
    <%= f.input :flat_nr, :input_html => { :size => 3 } , :hint => t('place.show.float_nr') %>
    <%= f.input :coordinates , :hint => t('place.show.coordinates') %>
    <%= f.input :place_type,:as => :select, :collection => PLACE_TYPE.sort , :hint => t('place.show.place_type') %>
    <%= f.input :floor_nr, :input_html => { :size => 3 } , :hint => t('place.show.floor_nr') %>
    <%= f.input :nr_of_floors, :input_html => { :size => 3 } , :hint => t('place.show.nr_of_floor') %>
    <%= f.input :nr_of_rooms, :input_html => { :size => 3 } , :hint => t('place.show.rooms') %>
    <%= f.input :surface, :input_html => { :size => 3 } , :hint => t('place.show.surface') %>
    <%= f.input :build_year, :input_html => { :size => 3 } , :hint => t('place.show.build') %>
    <%= f.input :heating_type, :input_html => { :size => 30 } , :hint => t('place.show.heating') %>
    <%= f.input :people_max,  :input_html => { :size => 3 } , :hint => t('place.show.people') %>
    <%= f.input :for_who, :input_html => { :size => 30 } , :hint => t('place.show.who') %>
    <%= f.input :min_length_lease,  :input_html => { :size => 30 } , :hint => t('place.show.length_min') %>
    <%= f.input :type_length_lease, :input_html => { :size => 30 } , :hint => t('place.show.type_length') %>
    <%= f.input :description , :hint => t('place.form.description') %>
    <%= f.input :has_balcony , :hint => t('place.show.balcony') %>
    <%= f.input :has_garage , :hint => t('place.show.garage') %>
    <%= f.input :has_basement , :hint => t('place.show.basement') %>
    <%= f.input :has_parking , :hint => t('place.show.parking') %>
    <%= f.input :has_internet , :hint => t('place.show.internet') %>
    <%= f.input :has_terrace , :hint => t('place.show.terrace') %>
    <%= f.input :has_lift , :hint => t('place.show.lift') %>
    <%= f.input :has_garden , :hint => t('place.show.garden') %>
	<%= f.input :is_active, :hint => t('place.form.is_active') %>
        <%= f.inputs :for => :images do |i| %>
              <% unless @place.images.empty? %>
               <%= image_tag(@place.images["#%i".to_i].image_url(:thumb).to_s) %>
                  <% unless i.object.new_record? %>
                    <%= i.input :remove_image, :as => :boolean %>
                   <% end %>
            <% end %>


            <%= i.input :image, :as => :file %>
            <%= i.input :image_cache, :as => :hidden %>


        <% end %>
  <% end %>
  
  <%= f.buttons do %>
    <%= f.commit_button %>
  <% end %>
<% end %>
</div>

app/views/places/_place.html.erb
	<div class="placee">
		
		<div class="where">
			<b><%= place.city %></b>, <%= place.district %><br/>
		</div>
		
		<% if place.is_active %>
			<div class="activity">
			<%=image_tag("active.png", :alt=>"Place Offer is active!", :width=>"25", :height=>"25")%>
			<span class="aaa"><%= t('place.placee.active') %></span>
			</div>
		<% end %>
		<div class="grade"><%= t('place.placee.average') %><%= place.grade %></div>
		<div class="prizes"><%= t('place.placee.prize_min') %><%= place.price_min %></div>
		<div class="placeInfo">	
			<b><%= t('place.placee.type') %></b> <%= place.place_type %>
			<b><%= t('place.placee.surface') %></b> <%= place.surface %>
			<b><%= t('place.placee.rooms') %></b><%= place.nr_of_rooms %>
			<b><%= t('place.placee.heating') %></b><%= place.heating_type %>
		</div>
		<div class="people">
			<b><%= t('place.placee.for') %></b><%= place.for_who %>
			<b><%= t('place.placee.people_max') %></b><%= place.people_max %>
		</div>
		<div class="dates">	
			<b><%= t('place.placee.avaible_from') %></b> <%= place.availability_from %>
			<b><%= t('place.placee.to') %></b><%= place.availability_to %>
		</div>
		<div class="options">
		<% if can? :read, place %>
			<%= link_to t('place.placee.show'), place%>
		<% end %>
		<% if can? :update, place %>		
				<%= link_to t('place.placee.edit'), edit_place_path(place) %>
		<% end %>
		<% if can? :destroy, place %>
			<%= link_to t('place.placee.delete'), place, :confirm => 'Are you sure?', :method => :delete %>
		<% end %>
		</div>
	
	</div>

app/views/places/_search.html.erb
<%= semantic_form_for @search , :remote => true do |f| %>
	<%= f.inputs do %>

    <%= f.input :city_contains, :label => t('place.search.city') , :input_html => { :size => 20 } %>
	<%= f.input :district_contains, :label => t('place.search.district') , :input_html => { :size => 20 } %>
	<%= f.input :price_min_gte, :label => t('place.search.price_min'), :input_html => { :size => 5 } %>
	<%= f.input :price_min_lte, :label => t('place.search.price_max'), :input_html => { :size => 5 } %>
	
	<%= f.input :grade_gte, :label => t('place.search.grade_min'), :input_html => { :size => 5 } %>
	<%= f.input :grade_lte, :label => t('place.search.grade_max'), :input_html => { :size => 5 } %>
	
	<%= f.input :place_type_contains,:label => t('place.search.type'), :as => :select, :collection => PLACE_TYPE.sort %>
	
	<!--	Nie działa ? --> <!--
	<%= f.input :country_equals, :priority_countries => [:pl, :gb, :de]%>
	<%= f.input :region_equals,:as => :select, :collection => REGIONS_PL.sort %>
	-->
	<% end %>
	<div class="knob">
	<%= f.buttons do %>
		<%= f.commit_button :label => t('place.search.search') %>
	<% end %>
	</div>
<% end %>

app/views/places/edit.html.erb
<% title t('place.edit.title') %>

<div class="form edit">
  <%= render 'form' %>
  <div class="link">
    <%= link_to t('place.edit.show'), @place, class: "btn primary" %>
    <%= link_to t('place.edit.back'), places_path, class: "btn primary" %>
  </div>
</div>

app/views/places/index.html.erb
<% title t('place.index.title') %>

	<div class="link">
	<% if can? :create, Place %>
		<%= link_to t('place.index.new_place'), new_place_path, class: "btn primary" %>
	<% end %>
		 <%= link_to t('place.index.show_all'), places_path, :remote => true, class: "btn primary" %>
	</div>
<article class="index">

<div class="seearch">
	<%= render :partial => 'search' %>
</div>

<div id="places">
	<%= render :partial => 'place', :collection => @places %>
</div><br>
<div id="paginator" class="paginator">
<%= paginate @places, :remote => true %>
</div>
</article>

app/views/places/index.js.erb
// render _place.html.erb partial
$("#places").html("<%= escape_javascript(render(@places)) %>");
// modify pagination links
$('#paginator').html('<%= escape_javascript(paginate(@places, :remote => true).to_s) %>');

app/views/places/new.html.erb
<% title t('place.new.title') %>

<div class="form new">
  <%= render :partial => 'form' %>
  <div class="link">
    <%= link_to t('place.new.back'), places_path, class: "btn primary" %>
  </div>
</div>

app/views/places/show.html.erb
<% title t('place.show.title') %>




  <% unless @place.images.empty?  %>
  
  <div id="gal" class="imageflow">
  
        <% for image in @place.images %>
            
            <%= image_tag image.image_url.to_s, :longdesc => image.image_url.to_s %>
            
       <% end %>

      </div>
  <% end %>
  <div class="show">
  
  <div class="show_header">
	<div class="availability">
		<span class="value"><%= t('place.show.active') %><%= @place.availability_from %><%= t('place.show.to') %><%= @place.availability_to %></span>
	</div>
	<div class="grade_stars"><%= @place.grade %></div>
	<input type="hidden" value="<%= @place.is_active %>" />
  </div>
  
   <div class="show_content">
  
  <div class="place_adress">
   <%= t('place.show.dane') %> <br />
    <%= t('place.show.owner')%> <%= link_to get_user_username(@place.user_id), user_path(@place.user_id)%> <br />
    <% if current_user.id == @place.user_id %>
        <%= t('place.show.telephone')%> <%= @place.telephone %> <br />
        <%= t('place.show.street')%> <%= @place.street %> <%= @place.place_nr %> / <%= @place.flat_nr %><br />
    <% end %>
	<%= t('place.show.district')%> <%= @place.district %> <br />
   <%= t('place.show.city')%> <%= @place.city %> <br />
   <%= t('place.show.region')%> <%= @place.region %> <br />
   <%= t('place.show.country')%> <%= @place.country %> <br />
  </div>
  
  <div class="place_price">
  <% t('place.show.price_min')%> <% @place.price_min %>
 <% t('place.show.price_max')%>  <% @place.price_max %>
   <h1 class= <% t('place.show.price_for_you') %> ><%= t('place.show.price_for_you')%> <%= (@place.price_max + @place.price_min)/2 %> </h1>
    <span class="deposit"><%= t('place.show.deposit')%><%= @place.deposit %></span>
  </div>  
  
  
  <div class="attribute">
    <span class="name"><%= t('place.show.coordinates')%></span>
    <span class="value"><%= @place.coordinates %></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t('place.show.place_type')%></span>
    <span class="value"><%= @place.place_type %></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t('place.show.floor_nr')%></span>
    <span class="value"><%= @place.floor_nr %></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t('place.show.nr_of_floor')%></span>
    <span class="value"><%= @place.nr_of_floors %></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t('place.show.rooms')%></span>
    <span class="value"><%= @place.nr_of_rooms %></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t('place.show.surface')%></span>
    <span class="value"><%= @place.surface %></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t('place.show.build')%></span>
    <span class="value"><%= @place.build_year %></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t('place.show.heating')%></span>
    <span class="value"><%= @place.heating_type %></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t('place.show.people')%></span>
    <span class="value"><%= @place.people_max %></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t('place.show.who')%></span>
    <span class="value"><%= @place.for_who %></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t('place.show.length_min')%></span>
    <span class="value"><%= @place.min_length_lease %></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t('place.show.type_length')%></span>
    <span class="value"><%= @place.type_length_lease %></span>
  </div>
  
  <div class="descripton">
    <h3>+ Rozwin opis</h3>
    <span class="full_descripton"><%= @place.description %></span>
  </div>
  <div class="attribute">
    <span class="name"><%= t('place.show.balcony')%></span><% if(@place.has_balcony ) %> <%=image_tag("active.png", :alt=>"true", :width=>"15", :height=>"15") %> <% else %> <%=image_tag("not_active.png", :alt=>"true", :width=>"15", :height=>"15") %> <% end %>
    <span class="name"><%= t('place.show.garage')%></span><% if(@place.has_garage) %> <%=image_tag("active.png", :alt=>"true", :width=>"15", :height=>"15") %> <% else %> <%=image_tag("not_active.png", :alt=>"true", :width=>"15", :height=>"15") %> <% end %>
    <span class="name"><%= t('place.show.basement')%></span><% if(@place.has_basement) %> <%=image_tag("active.png", :alt=>"true", :width=>"15", :height=>"15") %> <% else %> <%=image_tag("not_active.png", :alt=>"true", :width=>"15", :height=>"15") %> <% end %>
	<span class="name"><%= t('place.show.parking')%></span><% if(@place.has_parking) %> <%=image_tag("active.png", :alt=>"true", :width=>"15", :height=>"15") %> <% else %> <%=image_tag("not_active.png", :alt=>"true", :width=>"15", :height=>"15") %> <% end %>
	<span class="name"><%= t('place.show.internet')%></span><% if(@place.has_internet) %> <%=image_tag("active.png", :alt=>"true", :width=>"15", :height=>"15") %> <% else %> <%=image_tag("not_active.png", :alt=>"true", :width=>"15", :height=>"15") %> <% end %>
	<span class="name"><%= t('place.show.terrace')%></span><% if(@place.has_terrace) %> <%=image_tag("active.png", :alt=>"true", :width=>"15", :height=>"15") %> <% else %> <%=image_tag("not_active.png", :alt=>"true", :width=>"15", :height=>"15") %> <% end %>
	<span class="name"><%= t('place.show.lift')%></span> <% if(@place.has_lift) %> <%=image_tag("active.png", :alt=>"true", :width=>"15", :height=>"15") %> <% else %> <%=image_tag("not_active.png", :alt=>"true", :width=>"15", :height=>"15") %> <% end %>
	<span class="name"><%= t('place.show.garden')%></span><% if(@place.has_garden) %> <%=image_tag("active.png", :alt=>"true", :width=>"15", :height=>"15") %> <% else %> <%=image_tag("not_active.png", :alt=>"true", :width=>"15", :height=>"15") %> <% end %>
  </div>
  </div>
  <div class="link">
    <% if current_user.has_role? :owner %>
        <%= link_to t('place.show.edit'), edit_place_path(@place), class: "btn primary" %>
    <% end %>
    <% if current_user.has_role? :tenant %>
        <%= link_to 'New Request', new_request_path(:place_id => @place.id), class: "btn primary" %>
    <% end %>
    <%= link_to t('place.show.back'), places_path, class: "btn primary" %>
  </div>
  </div>
</div>