config/routes.rb
Zadziory::Application.routes.draw do

  resources :requests

  resources :authentications

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :preferences

  resources :places

  resources :histories

  resources :user_panel

  devise_for :users
  
  devise_scope :user do
	get "login", :to => "devise/sessions#new" 
	get "logout", :to => "devise/sessions#destroy"
	get "register", :to => "devise/registrations#new"
  end
  
  devise_for :users, :controllers => {:registrations => 'registrations'}
  
  match '/auth/:provider/callback' => 'authentications#create'

	get '/users/:id' => 'users#show', :as => "user"

		root :to => "places#index"

	get "myplaces" => "places#myPlaces", :as => "myplaces"
	get "panel" => "user_panel#index", :as => "panel"
	get "undefined" => "application#undefined_error", :as => "undefined"
	get '/user' => 'users#myAccount', :as => "my_account"

  get "allTenantRequests" => "requests#allTenantRequests", :as => "all_tenant_requests"
  get "pendingTenantRequests" => "requests#pendingTenantRequests", :as => "pending_tenant_requests"
  get "acceptedTenantRequests" => "requests#acceptedTenantRequests", :as => "accepted_tenant_requests"
  get "rentedTenantRequests" => "requests#rentedTenantRequests", :as => "rented_tenant_requests"
  get "rejectedTenantRequests" => "requests#rejectedTenantRequests", :as => "rejected_tenant_requests"

  get "allOwnerRequests" => "requests#allOwnerRequests", :as => "all_owner_requests"
  get "pendingOwnerRequests" => "requests#pendingOwnerRequests", :as => "pending_owner_requests"
  get "acceptedOwnerRequests" => "requests#acceptedOwnerRequests", :as => "accepted_owner_requests"
  get "rentedOwnerRequests" => "requests#rentedOwnerRequests", :as => "rented_owner_requests"
  get "rejectedOwnerRequests" => "requests#rejectedOwnerRequests", :as => "rejected_owner_requests"
end

app/helpers/layout_helper.rb
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  def show_title?
    @show_title
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset=utf-8>
    <title><%= content_for?(:title) ? yield(:title) : "Rentluk" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="images/logo1.png">
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <!--
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
    -->
    <%= csrf_meta_tags %>
    <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-28117571-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
  </head>

  <body>

    <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="/"><%=image_tag("logo3.png", :alt=>"Logo", :width=>"180")%></a>
          <ul class="nav">
            <li class="active"><a href="#"><%= t('layout.application.home') %></a></li>
            <li><a href="#about"><%= t('layout.application.about') %></a></li>
            <li><a href="#contact"><%= t('layout.application.contact') %></a></li>
          </ul>
          
		<div class="pull-right">
			 <% if user_signed_in? %>
				<span class="logged_as"><%= t('layout.application.logged') %> <%= current_user.username %>.</span>
				<%= link_to t('layout.application.panel'), panel_path %>
				<%= link_to t('layout.application.logout'), logout_path %>
			<% else %>
				<%= link_to t('layout.application.login'), login_path %>
				<%= link_to t('layout.application.register'), register_path %> 
			<% end %>
		</div>
			  <!--<form action="" class="pull-right">
            <input class="input-small" type="text" placeholder="Username">
            <input class="input-small" type="password" placeholder="Password">
            <button class="btn" type="submit">Sign in through GitHub</button>
            </form>
             -->   
        </div>
      </div>
    </div>

    <div class="container">
		
      <div class="content">
        <div class="page-header">
          <%= content_tag :h1, yield(:title) if show_title? %>
        </div>
        <div class="row">
			    <div id="flash">
				<% flash.each do |name, msg| %>
					<%= content_tag :div, msg, :id => "#{name}" %>
				<% end %>
                </div>

            <%= yield %>
        
        </div>
      </div>

      <footer>
        <p>&copy; RentLuk - projekt grupy zadziory</p>
      </footer>

    </div><!-- /container -->

  </body>
</html>